events {}

http {
  upstream authservice {
    server auth-service:3002;
  }

  upstream userservice {
    server user-service:3001;
  }

  server {
    listen 80;

    location /auth/ {
      proxy_pass http://authservice/;
    }

    location /user/ {
      proxy_pass http://userservice/;
    }

    location / {
      return 404 "Service not found";
    }
  }
}